#!/usr/bin/env bash
# E2E test for mutation-check.sh with the Go module (pinned mutago).
# Builds a git fixture: main has a tested function; a feature branch adds an
# untested one. Expects survivors + exit 1, then killing tests + exit 0.

set -uo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$SKILL_DIR/mutation-check.sh"

command -v go  >/dev/null || { echo "SKIP: go not on PATH"; exit 0; }
command -v git >/dev/null || { echo "SKIP: git not on PATH"; exit 0; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
cd "$WORK"

git init -qb main
printf 'module example.com/mutfix\n\ngo 1.26\n' > go.mod
cat > calc.go <<'EOF'
package calc

func Double(x int) int {
	return x * 2
}
EOF
cat > calc_test.go <<'EOF'
package calc

import "testing"

func TestDouble(t *testing.T) {
	if Double(3) != 6 {
		t.Fatal("3")
	}
	if Double(-2) != -4 {
		t.Fatal("-2")
	}
}
EOF
GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t \
  GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=commit.gpgsign GIT_CONFIG_VALUE_0=false \
  bash -c 'git add . && git commit -qm baseline'

git checkout -qb feature
cat >> calc.go <<'EOF'

func Sign(x int) int {
	if x < 0 {
		return -1
	}
	return 1
}
EOF
# A generated mock changed in the same commit must not be mutated: the parent
# filters it out of MUTATION_FILES, and nobody authors this code.
cat > mock_calc.go <<'EOF'
// Code generated by MockGen. DO NOT EDIT.

package calc

func MockScale(x int) int {
	if x < 0 {
		return -7
	}
	return 7
}
EOF
GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t \
  GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=commit.gpgsign GIT_CONFIG_VALUE_0=false \
  bash -c 'git add calc.go mock_calc.go && git commit -qm "add Sign untested, plus a generated mock"'

echo "--- phase 1: untested change, expect survivors ---"
RC=0
OUT="$("$SCRIPT" 2>&1)" || RC=$?
echo "$OUT"
[ "$RC" -eq 1 ] || { echo "FAIL: expected exit 1, got $RC"; exit 1; }
echo "$OUT" | grep -q 'SURVIVED'        || { echo "FAIL: no SURVIVED rows"; exit 1; }
echo "$OUT" | grep -q 'calc.go:'        || { echo "FAIL: no file:line in rows"; exit 1; }
echo "$OUT" | grep -q 'KILL_SURVIVORS'  || { echo "FAIL: no KILL_SURVIVORS directive"; exit 1; }
echo "$OUT" | grep -q 'Double'          && { echo "FAIL: unchanged function was mutated"; exit 1; }
echo "$OUT" | grep -q 'mock_calc.go'    && { echo "FAIL: generated mock was mutated"; exit 1; }
echo "$OUT" | grep -q 'MockScale'       && { echo "FAIL: generated mock function was mutated"; exit 1; }

echo "--- phase 1b: accept one survivor, expect count to drop by one ---"
TOTAL="$(grep -c ' SURVIVED  id=' <<< "$OUT")"
ONE_ID="$(grep -m1 ' SURVIVED  id=' <<< "$OUT" | sed 's/.*id=//')"
"$SCRIPT" --accept "$ONE_ID" >/dev/null || { echo "FAIL: --accept errored"; exit 1; }
RC=0
OUT="$("$SCRIPT" 2>&1)" || RC=$?
[ "$RC" -eq 1 ] || { echo "FAIL: expected exit 1 after single accept, got $RC"; exit 1; }
echo "$OUT" | grep -q "KILL_SURVIVORS: $((TOTAL - 1)) " || { echo "FAIL: accepted mutant still counted"; echo "$OUT" | grep KILL_SURVIVORS; exit 1; }

echo "--- phase 2: killing tests added, expect clean ---"
cat >> calc_test.go <<'EOF'

func TestSign(t *testing.T) {
	cases := map[int]int{-5: -1, -1: -1, 0: 1, 5: 1}
	for in, want := range cases {
		if got := Sign(in); got != want {
			t.Fatalf("Sign(%d) = %d, want %d", in, got, want)
		}
	}
}
EOF
GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t \
  GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=commit.gpgsign GIT_CONFIG_VALUE_0=false \
  bash -c 'git add calc_test.go && git commit -qm "kill mutants"'

RC=0
OUT="$("$SCRIPT" 2>&1)" || RC=$?
echo "$OUT"
[ "$RC" -eq 0 ] || { echo "FAIL: expected exit 0, got $RC"; exit 1; }
echo "$OUT" | grep -q 'MUTATION_OK' || { echo "FAIL: no MUTATION_OK"; exit 1; }

echo "--- phase 2b: a command's entry file is not measured, its sibling still is ---"
mkdir -p cmd/mutfix
cat > cmd/mutfix/main.go <<'EOF'
package main

import "fmt"

var greeting = "hi"

func helper(x int) int {
	if x < 0 {
		return -x
	}
	return x
}

func main() {
	fmt.Println(helper(3), greeting)
}
EOF
cat > cmd/mutfix/wire.go <<'EOF'
package main

func Wire(x int) int {
	if x < 0 {
		return -1
	}
	return 1
}
EOF
GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t \
  GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=commit.gpgsign GIT_CONFIG_VALUE_0=false \
  bash -c 'git add cmd/mutfix && git commit -qm "add untested main.go and sibling wire.go"'

RC=0
OUT="$("$SCRIPT" 2>&1)" || RC=$?
echo "$OUT"
[ "$RC" -eq 1 ] || { echo "FAIL: expected exit 1, got $RC"; exit 1; }
echo "$OUT" | grep -q 'cmd/mutfix/wire.go:' || { echo "FAIL: sibling file was not measured"; exit 1; }
echo "$OUT" | grep -q 'cmd/mutfix/main.go' && { echo "FAIL: command entry file was measured as production code"; exit 1; }

echo "--- phase 2c: the entry-file exclusion isn't anchored to the repo root ---"
mkdir -p svc/cmd/mutfix3
cat > svc/cmd/mutfix3/main.go <<'EOF'
package main

func helper(x int) int {
	if x < 0 {
		return -x
	}
	return x
}

var used = helper(3)

func main() {}
EOF
cat > svc/cmd/mutfix3/wire3.go <<'EOF'
package main

func Wire3(x int) int {
	if x > 5 {
		return -7
	}
	return 3
}
EOF
GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t \
  GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=commit.gpgsign GIT_CONFIG_VALUE_0=false \
  bash -c 'git add svc/cmd/mutfix3 && git commit -qm "add untested main.go under a non-root cmd/"'

RC=0
OUT="$("$SCRIPT" 2>&1)" || RC=$?
echo "$OUT"
[ "$RC" -eq 1 ] || { echo "FAIL: expected exit 1, got $RC"; exit 1; }
echo "$OUT" | grep -q 'svc/cmd/mutfix3/wire3.go:' || { echo "FAIL: sibling file was not measured"; exit 1; }
echo "$OUT" | grep -q 'svc/cmd/mutfix3/main.go' && { echo "FAIL: entry file under a non-root cmd/ was measured as production code"; exit 1; }

echo "--- phase 2d: the exclusion glob must not cross slashes past the entry file ---"
mkdir -p cmd/mutfix/deeper
cat > cmd/mutfix/deeper/main.go <<'EOF'
package main

func helper4(x int) int {
	if x > 9 {
		return -11
	}
	return 13
}
EOF
GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t \
  GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=commit.gpgsign GIT_CONFIG_VALUE_0=false \
  bash -c 'git add cmd/mutfix/deeper && git commit -qm "add a non-entry main.go nested under a root cmd/"'

RC=0
OUT="$("$SCRIPT" 2>&1)" || RC=$?
echo "$OUT"
[ "$RC" -eq 1 ] || { echo "FAIL: expected exit 1, got $RC"; exit 1; }
echo "$OUT" | grep -q 'cmd/mutfix/deeper/main.go:' || { echo "FAIL: a main.go nested deeper than the entry file was excluded from measurement"; exit 1; }

echo "--- phase 3: dirty worktree is rejected ---"
echo "// dirty" >> calc.go
RC=0
OUT="$("$SCRIPT" 2>&1)" || RC=$?
[ "$RC" -eq 2 ] || { echo "FAIL: expected exit 2 on dirty tree, got $RC"; exit 1; }
git checkout -q calc.go

echo "MUTATION GO OK"
