import io
import json
from pathlib import Path

from conftest import load_script

gate = load_script(Path(__file__).resolve().parent / "generated-file-gate.py")


def _run(monkeypatch, payload):
    monkeypatch.setattr("sys.stdin", io.StringIO(json.dumps(payload)))
    return gate.main()


def test_is_generated_checks_only_header_lines():
    body = "\n".join([f"line {i}" for i in range(gate.HEADER_LINES)]) + "\n// @generated"
    assert gate.is_generated(body) is False
    assert gate.is_generated("// @generated\nrest") is True


def test_is_generated_do_not_edit_phrase():
    assert gate.is_generated("// Code generated by tool. DO NOT EDIT.") is True
    assert gate.is_generated("// generated but nothing else") is False
    assert gate.is_generated("// DO NOT EDIT alone") is False


def test_no_path_is_allowed(monkeypatch):
    assert _run(monkeypatch, {"tool_input": {}}) == 0


def test_swagger_json_basename_is_blocked(monkeypatch, tmp_path, capsys):
    path = tmp_path / "swagger.json"
    rc = _run(monkeypatch, {"tool_input": {"file_path": str(path)}})
    assert rc == 2
    assert "no comment syntax" in capsys.readouterr().err


def test_generated_content_being_written_is_blocked(monkeypatch, tmp_path, capsys):
    path = tmp_path / "models.go"
    rc = _run(monkeypatch, {"tool_input": {"file_path": str(path), "content": "// @generated\npackage x"}})
    assert rc == 2
    assert "content being written says so" in capsys.readouterr().err


def test_generated_header_on_disk_is_blocked(monkeypatch, tmp_path, capsys):
    path = tmp_path / "models.go"
    path.write_text("// Code generated. DO NOT EDIT.\npackage x\n")
    rc = _run(monkeypatch, {"tool_input": {"file_path": str(path)}})
    assert rc == 2
    assert "says so in its header" in capsys.readouterr().err


def test_ordinary_file_is_allowed(monkeypatch, tmp_path):
    path = tmp_path / "models.go"
    path.write_text("package x\n")
    assert _run(monkeypatch, {"tool_input": {"file_path": str(path)}}) == 0


def test_missing_file_on_disk_is_allowed(monkeypatch, tmp_path):
    path = tmp_path / "nope.go"
    assert _run(monkeypatch, {"tool_input": {"file_path": str(path)}}) == 0


def test_non_dict_tool_input_is_a_no_op(monkeypatch):
    assert _run(monkeypatch, {"tool_input": "nope"}) == 0


def test_copilot_pre_tool_use_edit_resolves_relative_to_cwd(monkeypatch, tmp_path, capsys):
    path = tmp_path / "models.go"
    path.write_text("// Code generated. DO NOT EDIT.\npackage x\n")
    payload = {
        "hook_event_name": "PreToolUse",
        "host": "copilot",
        "session_id": "s1",
        "cwd": str(tmp_path),
        "tool_name": "Edit",
        "tool_input": {"path": "models.go"},
    }
    rc = _run(monkeypatch, payload)
    assert rc == 2
