#!/usr/bin/env bash
# Tests generated-file-gate.py: a file whose header marks it generated cannot be
# edited or written by hand, whatever its path; a hand-written file can.

set -uo pipefail

GATE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/generated-file-gate.py"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
failures=0

printf '// Code generated by sqlc. DO NOT EDIT.\n// versions:\n//   sqlc v1.30.0\n\npackage database\n' > "$WORK/task.sql.go"
printf '// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n' > "$WORK/cert.pb.go"
printf '# Generated by the protocol buffer compiler.  DO NOT EDIT!\n\nimport sys\n' > "$WORK/pb2.py"
printf '/* @generated */\nexport const x = 1\n' > "$WORK/bundle.ts"
printf 'package taskengine\n\nfunc F() int { return 1 }\n' > "$WORK/hand.go"
printf '// This file documents how the generator works.\n// Regenerate with make gen-models.\n\npackage docs\n' > "$WORK/notes.go"
printf 'package p\n\n// an ordinary comment near the top\n' > "$WORK/deep.go"
for i in $(seq 1 12); do echo "// filler $i" >> "$WORK/deep.go"; done
echo "// Code generated by x. DO NOT EDIT." >> "$WORK/deep.go"

# want: BLOCK | ALLOW
expect() {
  local label="$1" want="$2" payload="$3" rc=0 out got
  out="$(printf '%s' "$payload" | python3 "$GATE" 2>&1)" || rc=$?
  if [ "$rc" -eq 0 ]; then
    got=ALLOW
  elif printf '%s' "$out" | grep -q 'generated-file-gate:'; then
    got=BLOCK
  else
    got="OTHER($rc)"
  fi
  if [ "$got" = "$want" ]; then
    printf '  ok:   %-46s %s\n' "$label" "$got"
  else
    printf '  FAIL: %-46s got %s want %s\n' "$label" "$got" "$want"
    failures=$((failures + 1))
  fi
}

edit() { jq -nc --arg p "$1" '{tool_name:"Edit", tool_input:{file_path:$p, old_string:"a", new_string:"b"}}'; }
write() { jq -nc --arg p "$1" --arg c "$2" '{tool_name:"Write", tool_input:{file_path:$p, content:$c}}'; }
copilot_edit() {
  python3 - "$1" "$2" <<'PY'
import json
import sys

cwd, file_path = sys.argv[1:3]
json.dump(
    {
        "hook_event_name": "PreToolUse",
        "session_id": "copilot-generated",
        "cwd": cwd,
        "tool_name": "Edit",
        "tool_input": {
            "path": file_path,
            "old_string": "a",
            "new_string": "b",
        },
    },
    sys.stdout,
)
PY
}
copilot_write() {
  python3 - "$1" "$2" "$3" <<'PY'
import json
import sys

cwd, file_path, content = sys.argv[1:4]
json.dump(
    {
        "hook_event_name": "PreToolUse",
        "session_id": "copilot-generated",
        "cwd": cwd,
        "tool_name": "Write",
        "tool_input": {
            "path": file_path,
            "content": content,
        },
    },
    sys.stdout,
)
PY
}
copilot_missing_path() {
  python3 - "$1" "$2" <<'PY'
import json
import sys

cwd, tool_name = sys.argv[1:3]
json.dump(
    {
        "hook_event_name": "PreToolUse",
        "session_id": "copilot-generated",
        "cwd": cwd,
        "tool_name": tool_name,
        "tool_input": {},
    },
    sys.stdout,
)
PY
}

echo "a generated header refuses the edit, whatever the generator"
expect "sqlc"                       BLOCK "$(edit "$WORK/task.sql.go")"
expect "protoc-gen-go"              BLOCK "$(edit "$WORK/cert.pb.go")"
expect "python protobuf"            BLOCK "$(edit "$WORK/pb2.py")"
expect "@generated"                 BLOCK "$(edit "$WORK/bundle.ts")"
expect "writing fresh generated content" \
                                    BLOCK "$(write "$WORK/new.go" '// Code generated by sqlc. DO NOT EDIT.
package database')"

echo "artifacts with nowhere to carry a marker are named outright"
mkdir -p "$WORK/docs"
printf '{\n  "swagger": "2.0"\n}\n' > "$WORK/docs/swagger.json"
printf 'swagger: "2.0"\n' > "$WORK/docs/swagger.yaml"
expect "swagger.json has no comment syntax"  BLOCK "$(edit "$WORK/docs/swagger.json")"
expect "swagger.yaml alongside it"           BLOCK "$(edit "$WORK/docs/swagger.yaml")"
expect "swagger.json anywhere, not one path" BLOCK "$(edit "$WORK/nested/api/swagger.json")"

echo "hand-written files are untouched"
printf '{\n  "openapi": "3.0.0"\n}\n' > "$WORK/openapi.json"
expect "a differently named spec is not assumed" ALLOW "$(edit "$WORK/openapi.json")"
expect "ordinary source"            ALLOW "$(edit "$WORK/hand.go")"
expect "prose merely naming the generator" \
                                    ALLOW "$(edit "$WORK/notes.go")"
expect "marker below the header window" ALLOW "$(edit "$WORK/deep.go")"
expect "file that does not exist yet" ALLOW "$(edit "$WORK/absent.go")"
expect "no file_path in the input"   ALLOW '{"tool_name":"Edit","tool_input":{}}'

echo "copilot pre-tool payloads hit the same file boundary"
expect "copilot generated marker via relative path" \
                                    BLOCK "$(copilot_edit "$WORK" "task.sql.go")"
expect "copilot writing fresh generated content" \
                                    BLOCK "$(copilot_write "$WORK" "fresh.pb.go" '// Code generated by protoc-gen-go. DO NOT EDIT.

package pb')"
expect "copilot ordinary source via relative path" \
                                    ALLOW "$(copilot_edit "$WORK" "hand.go")"
# This gate applies everywhere and has no repo-specific prerequisite it can
# verify first, so a missing path stays allow-open: without a target file there
# is no evidence to check, unlike contributing-gate.py's opted-in guide policy.
expect "copilot missing path stays allow-open" \
                                    ALLOW "$(copilot_missing_path "$WORK" "Edit")"

echo ""
if [ "$failures" -eq 0 ]; then
  echo "GENERATED FILE GATE OK"
else
  echo "FAILED: $failures assertion(s)"
  exit 1
fi
